create table appointments (id bigint not null auto_increment, created datetime(6), end_time datetime(6) not null, last_update datetime(6), remark varchar(255), start_time datetime(6) not null, doctor_id bigint not null, patient_id bigint not null, primary key (id)) engine=InnoDB;
create table daily_schedule (id bigint not null auto_increment, end time not null, start time not null, primary key (id)) engine=InnoDB;
create table department (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table doctors_speciality (doctor_id bigint not null, speciality_id bigint not null) engine=InnoDB;
create table holiday (id bigint not null auto_increment, description varchar(255), end datetime(6) not null, start datetime(6) not null, profile_id bigint, primary key (id)) engine=InnoDB;
create table profile (id bigint not null auto_increment, about varchar(255), address varchar(255), date_of_birth date, degree varchar(255), email varchar(255) not null, first_name varchar(255) not null, gender varchar(255), last_name varchar(255) not null, office integer, social_number varchar(255), telephone varchar(255), schedule bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table role (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table speciality (id bigint not null auto_increment, name varchar(255) not null, department_id bigint not null, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, created datetime(6), last_update datetime(6), login varchar(255) not null, password varchar(255) not null, status integer not null, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
create table weekly_schedule (id bigint not null auto_increment, friday bigint, monday bigint, saturday bigint, sunday bigint, thursday bigint, tuesday bigint, wednesday bigint, primary key (id)) engine=InnoDB;

alter table profile add constraint UK_9d5dpsf2ufa6rjbi3y0elkdcd unique (email);
alter table user add constraint UK_ew1hvam8uwaknuaellwhqchhb unique (login);
alter table appointments add constraint FKc3iel9i2t7b8bpwf59csh5yof foreign key (doctor_id) references user (id);
alter table appointments add constraint FKrfkx6dhjo4mk33qifb3x5v57j foreign key (patient_id) references user (id);
alter table doctors_speciality add constraint FKgfc2qdo5yoohcxptdq9nhe2hd foreign key (speciality_id) references speciality (id);
alter table doctors_speciality add constraint FKl5wmmi0jlb7kd5026cicj91t5 foreign key (doctor_id) references profile (id);
alter table holiday add constraint FKiloeama6w3g9o7s3fojtkpdrd foreign key (profile_id) references profile (id);
alter table profile add constraint FKffsvrknrs7aqthv7kg3x15of6 foreign key (schedule) references weekly_schedule (id);
alter table profile add constraint FKawh070wpue34wqvytjqr4hj5e foreign key (user_id) references user (id);
alter table speciality add constraint FK2eyownqehfoodivhopcdg9q63 foreign key (department_id) references department (id);
alter table user_roles add constraint FKrhfovtciq1l558cw6udg0h0d3 foreign key (role_id) references role (id);
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k foreign key (user_id) references user (id);
alter table weekly_schedule add constraint FK8dhtvjii11moqpyyl98dd2rjy foreign key (friday) references daily_schedule (id);
alter table weekly_schedule add constraint FK4l4itk1n1se59i48yecqjekpj foreign key (monday) references daily_schedule (id);
alter table weekly_schedule add constraint FK70tmcyea8ut06bw329up306op foreign key (saturday) references daily_schedule (id);
alter table weekly_schedule add constraint FKswlvxpfynvmoitu69p5w3y4xb foreign key (sunday) references daily_schedule (id);
alter table weekly_schedule add constraint FKigva7lcn0sgw01r2bn7c8011 foreign key (thursday) references daily_schedule (id);
alter table weekly_schedule add constraint FKc298uwtj0n1701s893qftxuqr foreign key (tuesday) references daily_schedule (id);
alter table weekly_schedule add constraint FKhmpeu96hv2nib5an721ufwbxt foreign key (wednesday) references daily_schedule (id);